services:
  redis-db:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: redis-db

  redis-go-server:
    build: 
      context: ../
      dockerfile: ./deploy/Dockerfile
    environment:
      - REDIS_DB_URL=redis-db:6379
      - REDIS_DB_PASSWORD=
      - REDIS_DB=0
    ports:
      - 8080:8080
    depends_on:
      - redis-db
    container_name: redis-go-server
